---
- name: configuring all machines
  hosts: general
  become: true
  tasks:
    - name: installing epel-release package and ntp
      yum: name=['epel-release', 'ntp'] state=installed 
 
    - name: start ntpd
      service:
        name: ntpd
        state: started
