- name: install node and npm
  yum:
    name: ['nodejs', 'npm']
    state: present

- name: install forever package
  npm: name=forever state=present global=yes

- name: create nodejs path
  file: 
    path: /var/nodejs
    state: directory

- name: copy nodeJS server files
  copy:
    src: nodeJS_server
    dest: /var/nodejs/

- name: change directory and install dependencies
  command: chdir=/var/nodejs/nodeJS_server/ npm install

- name: check running nodejs application
  command: forever list
  register: forever_list
  changed_when: false

- name: start nodejs app
  command: forever start /var/nodejs/nodeJS_server/index.js
  when: " forever_list.stdout.find('/var/nodejs/nodeJS_server/index.js') == -1"
