- name: adding mongo repo
  copy:
    src: mongodb-org.repo
    dest: /etc/yum.repos.d/
- name: installing Mongo DB
  yum:
    name: mongodb-org
    state: present
- name: start MongoDB
  service:
    name: mongod
    state: started
